#!/usr/bin/env bash
# Generated by blq ci generate
# Command: test
# Description: Run pytest test suite
#
# Usage: ./test.sh [extra args...]

set -euo pipefail

# Check if blq is available for log capture
if command -v blq &> /dev/null && [ -d ".lq" ]; then
    # Use blq to capture and parse output
    if [ $# -gt 0 ]; then
        blq run test -- "$@"
    else
        blq run test
    fi
else
    # Fallback: run command directly
    CMD='.venv/bin/python -m pytest tests/ -v'
    if [ $# -gt 0 ]; then
        CMD="$CMD $*"
    fi
    echo "Running: $CMD"
    eval "$CMD"
fi
