#!/usr/bin/env bash
# Generated by blq ci generate
# Command: typecheck
# Description: Run mypy type checker
#
# Usage: ./typecheck.sh [extra args...]

set -euo pipefail

# Check if blq is available for log capture
if command -v blq &> /dev/null && [ -d ".lq" ]; then
    # Use blq to capture and parse output
    if [ $# -gt 0 ]; then
        blq run typecheck -- "$@"
    else
        blq run typecheck
    fi
else
    # Fallback: run command directly
    CMD='.venv/bin/python -m mypy src/jetsam/'
    if [ $# -gt 0 ]; then
        CMD="$CMD $*"
    fi
    echo "Running: $CMD"
    eval "$CMD"
fi
